version: 2
jobs:
  build:
    docker:
      - image: hashicorp/terraform:0.11.11

    working_directory: ~/kp-infra

    steps:
     - checkout
     - run: terraform workspace new dev
     - run: terraform workspace select dev
     - run: terraform init
        name: terraform init
        command: |
          terraform init -input=false

     - run:
        name: terraform plan
        command: |
          terraform plan
